package com.css.pos.model.service;

import com.css.pos.model.service.common.AdminModule;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 25 22:01:14 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminModuleImpl extends ApplicationModuleImpl implements AdminModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AdminModuleImpl() {
    }

    /**
     * Container's getter for PosIntCountriesUPView.
     * @return PosIntCountriesUPView
     */
    public ViewObjectImpl getPosIntCountriesUPView() {
        return (ViewObjectImpl) findViewObject("PosIntCountriesUPView");
    }
    public void clearCountriesData(){
        ViewObjectImpl countriesUPView = getPosIntCountriesUPView();
        countriesUPView.setRangeSize(-1);
        Row[] allRowsInRange = countriesUPView.getAllRowsInRange();
        for(Row row :allRowsInRange ){
            row.remove();
        }
//        Row first = countriesUPView.first();
//        if(first != null){
//            first.remove();
//        }
//        while(countriesUPView.hasNext()){
//            countriesUPView.next().remove();
//        }
        getDBTransaction().commit();
    }
}