package com.css.pos.model.service;

import com.css.pos.model.service.common.AdminModule;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 25 22:01:14 EET 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdminModuleImpl extends ApplicationModuleImpl implements AdminModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AdminModuleImpl() {
    }

    /**
     * Container's getter for PosIntCountriesUPView.
     * @return PosIntCountriesUPView
     */
    public ViewObjectImpl getPosIntCountriesUPView() {
        return (ViewObjectImpl) findViewObject("PosIntCountriesUPView");
    }
    public void clearCountriesData(){
        ViewObjectImpl countriesUPView = getPosIntCountriesUPView();
        countriesUPView.setRangeSize(-1);
        Row[] allRowsInRange = countriesUPView.getAllRowsInRange();
        for(Row row :allRowsInRange ){
            row.remove();
        }
//        Row first = countriesUPView.first();
//        if(first != null){
//            first.remove();
//        }
//        while(countriesUPView.hasNext()){
//            countriesUPView.next().remove();
//        }
        getDBTransaction().commit();
    }
    
    //Genric method to clear any VO rows
    public void clearVOData(String voName){
        ViewObjectImpl anyVO =(ViewObjectImpl) findViewObject(voName);
        anyVO.setRangeSize(-1);
        Row[] allRowsInRange = anyVO.getAllRowsInRange();
        for(Row row :allRowsInRange ){
            row.remove();
        }
        getDBTransaction().commit();
    }

    /**
     * Container's getter for PosStoreUPView1.
     * @return PosStoreUPView1
     */
    public ViewObjectImpl getPosStoreUPView() {
        return (ViewObjectImpl) findViewObject("PosStoreUPView");
    }

    /**
     * Container's getter for PosStoreBranchUPView1.
     * @return PosStoreBranchUPView1
     */
    public ViewObjectImpl getPosStoreBranchUPView1() {
        return (ViewObjectImpl) findViewObject("PosStoreBranchUPView1");
    }

    /**
     * Container's getter for PosStoreBranchsUPFk1Link1.
     * @return PosStoreBranchsUPFk1Link1
     */
    public ViewLinkImpl getPosStoreBranchsUPFk1Link1() {
        return (ViewLinkImpl) findViewLink("PosStoreBranchsUPFk1Link1");
    }

    /**
     * Container's getter for PosWarehouseUPView1.
     * @return PosWarehouseUPView1
     */
    public ViewObjectImpl getPosWarehouseUPView2() {
        return (ViewObjectImpl) findViewObject("PosWarehouseUPView2");
    }

    /**
     * Container's getter for PosWarehousesUPFk1Link1.
     * @return PosWarehousesUPFk1Link1
     */
    public ViewLinkImpl getPosWarehousesUPFk1Link1() {
        return (ViewLinkImpl) findViewLink("PosWarehousesUPFk1Link1");
    }
}
