package com.css.pos.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 25 22:03:54 EET 2020
// ---------------------------------------------------------------------
public interface AdminModule extends ApplicationModule {
    void clearCountriesData();

    void clearVOData(String voName);
}

